import { forwardRef } from "react";
import Head from "next/head";
import Intro from "../components/Intro";
import Projects from "../components/Projects";
import styles from "../styles/Home.module.sass";
import Contact from "../components/Contact";

const Home = forwardRef<HTMLDivElement>((_props, ref) => (
  <div className={styles.home__container} ref={ref}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta lang="en-gb" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Intro />
    <Projects />
    <Contact />
  </div>
));
Home.displayName = "Home";

export default Home;
