import { useRef } from "react";
import { useIsLandscape } from "../hooks/useIsLandscape";
import Head from "next/head";
import HorizontalNavigation from "../components/HorizontalNavigation";
import Home from "../components/Home";
import styles from "../styles/Home.module.sass";

const App = () => {
  const hasScreenLandscapeOrientation = useIsLandscape();
  const containerRef = useRef<HTMLDivElement | null>(null);

  return (
    <>
      {" "}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta lang="en-gb" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {hasScreenLandscapeOrientation ? (
        <HorizontalNavigation containerRef={containerRef}>
          <div className={styles.home__container} ref={containerRef}>
            <Home />
          </div>
        </HorizontalNavigation>
      ) : (
        <Home />
      )}
    </>
  );
};
App.displayName = "App";

export default App;
